"""simplify doctor profile

Revision ID: 12eb4a6a5bc4
Revises: e08fa2fdbc02
Create Date: 2026-07-07 13:43:29.054337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12eb4a6a5bc4'
down_revision: Union[str, Sequence[str], None] = 'e08fa2fdbc02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    bind = op.get_bind()

    appointment_statuses = postgresql.ENUM(
        "SCHEDULED",
        "COMPLETED",
        "CANCELED",
        name="appointment_statuses",
    )
    appointment_statuses.create(bind, checkfirst=True)

    genders = postgresql.ENUM(
        "MAN",
        "WOMAN",
        name="genders",
    )
    genders.create(bind, checkfirst=True)

    op.drop_table("appointments")
    op.drop_table("doctor_profiles")
    op.drop_table("patient_profiles")

    op.create_table(
        "patient_profiles",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("full_name", sa.String(length=150), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=False),
        sa.Column(
            "gender",
            postgresql.ENUM("MAN", "WOMAN", name="genders", create_type=False),
            nullable=False,
        ),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=False),
    )

    op.create_table(
        "doctor_profiles",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("full_name", sa.String(length=150), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False, unique=True),
        sa.Column("specialization", sa.String(length=100), nullable=False),
        sa.Column("experience_years", sa.Integer(), nullable=False),
    )

    op.create_table(
        "appointments",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("patient_id", sa.Integer(), sa.ForeignKey("patient_profiles.id"), nullable=False),
        sa.Column("doctor_id", sa.Integer(), sa.ForeignKey("doctor_profiles.id"), nullable=False),
        sa.Column("appointment_date", sa.Date(), nullable=False),
        sa.Column("appointment_time", sa.Time(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "SCHEDULED",
                "COMPLETED",
                "CANCELED",
                name="appointment_statuses",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.String(length=255), nullable=False),
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_profiles', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('patient_profiles_user_id_fkey', 'patient_profiles', 'users', ['user_id'], ['id'])
    op.create_unique_constraint('patient_profiles_user_id_key', 'patient_profiles', ['user_id'])
    op.drop_column('patient_profiles', 'phone')
    op.drop_column('patient_profiles', 'full_name')
    op.add_column('doctor_profiles', sa.Column('employment_type', postgresql.ENUM('FULL_TIME', 'PART_TIME', name='employment_type'), autoincrement=False, nullable=False))
    op.add_column('doctor_profiles', sa.Column('bio', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('doctor_profiles', sa.Column('years_experience', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('doctor_profiles', sa.Column('hospital_branch', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('doctor_profiles', sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('doctor_profiles', sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.create_foreign_key('doctor_profiles_doctor_id_fkey', 'doctor_profiles', 'users', ['doctor_id'], ['id'])
    op.drop_constraint(None, 'doctor_profiles', type_='unique')
    op.drop_column('doctor_profiles', 'experience_years')
    op.drop_column('doctor_profiles', 'email')
    op.drop_column('doctor_profiles', 'phone')
    op.drop_column('doctor_profiles', 'full_name')
    op.drop_column('doctor_profiles', 'id')
    op.add_column('appointments', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('appointment_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('appointments', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('reason_for_visit', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('scheduled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key('appointments_doctor_id_fkey', 'appointments', 'doctor_profiles', ['doctor_id'], ['doctor_id'])
    op.alter_column('appointments', 'status',
               existing_type=sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELED', name='appointment_statuses'),
               type_=postgresql.ENUM('SCHEDULED', 'COMPLETED', 'CANCELLED', name='appointment_status'),
               existing_nullable=False)
    op.drop_column('appointments', 'reason')
    op.drop_column('appointments', 'appointment_time')
    op.drop_column('appointments', 'appointment_date')
    op.drop_column('appointments', 'id')
    # ### end Alembic commands ###
