"""create tables

Revision ID: cc64ad8b5fb1
Revises: c14e93f69c13
Create Date: 2026-06-27 12:46:34.937263

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "cc64ad8b5fb1"
down_revision: Union[str, Sequence[str], None] = "c14e93f69c13"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
