"""add bio to doctor profile

Revision ID: e08fa2fdbc02
Revises: 7146be507190
Create Date: 2026-07-05 09:35:26.313233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e08fa2fdbc02'
down_revision: Union[str, Sequence[str], None] = '7146be507190'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_profiles', sa.Column('bio', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor_profiles', 'bio')
    # ### end Alembic commands ###
